AWS_ACCESS_KEY: "AKIAXK5FON5GSFH3DHTC"
AWS_SECRET_KEY: "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"
AWS_BUCKET: "corys-image-bucket"
AWS_REGION:     "us-east-1"

SECRET_KEY: 'sk_test_hIgvJgy28wkTgImS9EZBTuig00QM5eWOIu'
PUBLISHABLE_KEY: 'pk_test_VJu4ZFBLRvD0nbyx7BREtHbt00pjcd5jGh'