AWS_ACCESS_KEY: "AKIATHM5OWA6UIWHT2B4"
AWS_SECRET_KEY: "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"
AWS_BUCKET:     "cory-rucker-user"
AWS_REGION:     "us-east-1"

SECRET_KEY: 'sk_test_hIgvJgy28wkTgImS9EZBTuig00QM5eWOIu'
PUBLISHABLE_KEY: 'pk_test_VJu4ZFBLRvD0nbyx7BREtHbt00pjcd5jGh'